services:
  jenkins-controller:
    image: jenkins/jenkins:lts
    container_name: jenkins-controller
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins-network

  ssh-agent:
    build:
      context: .
      dockerfile: Dockerfile.ssh_agent
    container_name: ssh-agent
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=${JENKINS_AGENT_SSH_PUBKEY}
    volumes:
      - jenkins_agent_volume:/home/jenkins/agent
    depends_on:
      - jenkins-controller
    networks:
      - jenkins-network
    expose:
      - "22"

  ansible-agent:
    build:
      context: .
      dockerfile: Dockerfile.ansible_agent
    container_name: ansible-agent
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=${JENKINS_ANSIBLE_AGENT_PUBKEY}
    volumes:
      - ansible_agent_volume:/home/jenkins/agent
      - ./ansible:/home/jenkins/ansible
    depends_on:
      - jenkins-controller
    networks:
      - jenkins-network
    expose:
      - "22"

  test-server:
    build:
      context: .
      dockerfile: Dockerfile.test_server
    container_name: test-server
    hostname: test-server
    networks:
      - jenkins-network
    expose:
      - "22"
    ports:
      - "2222:22"
      - "8081:80"

volumes:
  jenkins_home:
  jenkins_agent_volume:
  ansible_agent_volume:

networks:
  jenkins-network:
    driver: bridge